### ISSUE TITLE
CORS issues when binding images. 

### ISSUE THREAD

**Issue by donnie24** [jofftiquez/vue-croppie#45] opened 2018-11-15 08:19 UTC
Do you have any solution abut CORS issue? Thanks

**Comment by jofftiquez** [comment] 2018-11-15 08:47
Are you trying to bind an image from a url?

**Comment by donnie24** [comment] 2018-11-16 02:11
Yes, im try to bind an image let say from s3 server.

**Comment by jofftiquez** [comment] 2018-11-16 03:04
Maybe your s3 server cors configuration is blocking the localhost? In my demo, those images are also from an online url.

**Comment by donnie24** [comment] 2018-11-16 04:53
in the s3 configuration is already set. i will provide image url and try to test. 
Try this url https://fdca.s3-ap-southeast-2.amazonaws.com/c23d8a72-21f6-4c19-bad3-93601011ca42.jpg

thanks

**Comment by jofftiquez** [comment] 2018-11-16 05:53
@donnie24 I was able to bind the image look here. http://vue-croppie.surge.sh/

How do you server you localhost enviroment?

**Comment by jofftiquez** [comment] 2018-11-16 05:56
I will close this issue now because the problem is not within the plugin. You can still ask questions related to this issue here. I will see what I can help you with.

**Closed as completed by jofftiquez** 2018-11-16 05:56 UTC
